/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistPlaylistSlugRouteImport } from './routes/playlist.$playlistSlug'
import { Route as ArtistArtistSlugRouteImport } from './routes/artist.$artistSlug'
import { Route as AlbumAlbumSlugRouteImport } from './routes/album.$albumSlug'
import { Route as ArtistArtistSlugIndexRouteImport } from './routes/artist.$artistSlug.index'
import { Route as ArtistArtistSlugAlbumAlbumSlugRouteImport } from './routes/artist.$artistSlug.album.$albumSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistSlugRoute = PlaylistPlaylistSlugRouteImport.update({
  id: '/playlist/$playlistSlug',
  path: '/playlist/$playlistSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistArtistSlugRoute = ArtistArtistSlugRouteImport.update({
  id: '/artist/$artistSlug',
  path: '/artist/$artistSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumAlbumSlugRoute = AlbumAlbumSlugRouteImport.update({
  id: '/album/$albumSlug',
  path: '/album/$albumSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistArtistSlugIndexRoute = ArtistArtistSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistArtistSlugRoute,
} as any)
const ArtistArtistSlugAlbumAlbumSlugRoute =
  ArtistArtistSlugAlbumAlbumSlugRouteImport.update({
    id: '/album/$albumSlug',
    path: '/album/$albumSlug',
    getParentRoute: () => ArtistArtistSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album/$albumSlug': typeof AlbumAlbumSlugRoute
  '/artist/$artistSlug': typeof ArtistArtistSlugRouteWithChildren
  '/playlist/$playlistSlug': typeof PlaylistPlaylistSlugRoute
  '/artist/$artistSlug/': typeof ArtistArtistSlugIndexRoute
  '/artist/$artistSlug/album/$albumSlug': typeof ArtistArtistSlugAlbumAlbumSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album/$albumSlug': typeof AlbumAlbumSlugRoute
  '/playlist/$playlistSlug': typeof PlaylistPlaylistSlugRoute
  '/artist/$artistSlug': typeof ArtistArtistSlugIndexRoute
  '/artist/$artistSlug/album/$albumSlug': typeof ArtistArtistSlugAlbumAlbumSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album/$albumSlug': typeof AlbumAlbumSlugRoute
  '/artist/$artistSlug': typeof ArtistArtistSlugRouteWithChildren
  '/playlist/$playlistSlug': typeof PlaylistPlaylistSlugRoute
  '/artist/$artistSlug/': typeof ArtistArtistSlugIndexRoute
  '/artist/$artistSlug/album/$albumSlug': typeof ArtistArtistSlugAlbumAlbumSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album/$albumSlug'
    | '/artist/$artistSlug'
    | '/playlist/$playlistSlug'
    | '/artist/$artistSlug/'
    | '/artist/$artistSlug/album/$albumSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album/$albumSlug'
    | '/playlist/$playlistSlug'
    | '/artist/$artistSlug'
    | '/artist/$artistSlug/album/$albumSlug'
  id:
    | '__root__'
    | '/'
    | '/album/$albumSlug'
    | '/artist/$artistSlug'
    | '/playlist/$playlistSlug'
    | '/artist/$artistSlug/'
    | '/artist/$artistSlug/album/$albumSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumAlbumSlugRoute: typeof AlbumAlbumSlugRoute
  ArtistArtistSlugRoute: typeof ArtistArtistSlugRouteWithChildren
  PlaylistPlaylistSlugRoute: typeof PlaylistPlaylistSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistSlug': {
      id: '/playlist/$playlistSlug'
      path: '/playlist/$playlistSlug'
      fullPath: '/playlist/$playlistSlug'
      preLoaderRoute: typeof PlaylistPlaylistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$artistSlug': {
      id: '/artist/$artistSlug'
      path: '/artist/$artistSlug'
      fullPath: '/artist/$artistSlug'
      preLoaderRoute: typeof ArtistArtistSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumSlug': {
      id: '/album/$albumSlug'
      path: '/album/$albumSlug'
      fullPath: '/album/$albumSlug'
      preLoaderRoute: typeof AlbumAlbumSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$artistSlug/': {
      id: '/artist/$artistSlug/'
      path: '/'
      fullPath: '/artist/$artistSlug/'
      preLoaderRoute: typeof ArtistArtistSlugIndexRouteImport
      parentRoute: typeof ArtistArtistSlugRoute
    }
    '/artist/$artistSlug/album/$albumSlug': {
      id: '/artist/$artistSlug/album/$albumSlug'
      path: '/album/$albumSlug'
      fullPath: '/artist/$artistSlug/album/$albumSlug'
      preLoaderRoute: typeof ArtistArtistSlugAlbumAlbumSlugRouteImport
      parentRoute: typeof ArtistArtistSlugRoute
    }
  }
}

interface ArtistArtistSlugRouteChildren {
  ArtistArtistSlugIndexRoute: typeof ArtistArtistSlugIndexRoute
  ArtistArtistSlugAlbumAlbumSlugRoute: typeof ArtistArtistSlugAlbumAlbumSlugRoute
}

const ArtistArtistSlugRouteChildren: ArtistArtistSlugRouteChildren = {
  ArtistArtistSlugIndexRoute: ArtistArtistSlugIndexRoute,
  ArtistArtistSlugAlbumAlbumSlugRoute: ArtistArtistSlugAlbumAlbumSlugRoute,
}

const ArtistArtistSlugRouteWithChildren =
  ArtistArtistSlugRoute._addFileChildren(ArtistArtistSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumAlbumSlugRoute: AlbumAlbumSlugRoute,
  ArtistArtistSlugRoute: ArtistArtistSlugRouteWithChildren,
  PlaylistPlaylistSlugRoute: PlaylistPlaylistSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
