/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistPlaylistNameRouteImport } from './routes/playlist.$playlistName'
import { Route as ArtistArtistNameRouteImport } from './routes/artist.$artistName'
import { Route as AlbumAlbumTitleRouteImport } from './routes/album.$albumTitle'
import { Route as ArtistArtistNameIndexRouteImport } from './routes/artist.$artistName.index'
import { Route as ArtistArtistNameAlbumAlbumSlugRouteImport } from './routes/artist.$artistName.album.$albumSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistPlaylistNameRoute = PlaylistPlaylistNameRouteImport.update({
  id: '/playlist/$playlistName',
  path: '/playlist/$playlistName',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistArtistNameRoute = ArtistArtistNameRouteImport.update({
  id: '/artist/$artistName',
  path: '/artist/$artistName',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumAlbumTitleRoute = AlbumAlbumTitleRouteImport.update({
  id: '/album/$albumTitle',
  path: '/album/$albumTitle',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistArtistNameIndexRoute = ArtistArtistNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistArtistNameRoute,
} as any)
const ArtistArtistNameAlbumAlbumSlugRoute =
  ArtistArtistNameAlbumAlbumSlugRouteImport.update({
    id: '/album/$albumSlug',
    path: '/album/$albumSlug',
    getParentRoute: () => ArtistArtistNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album/$albumTitle': typeof AlbumAlbumTitleRoute
  '/artist/$artistName': typeof ArtistArtistNameRouteWithChildren
  '/playlist/$playlistName': typeof PlaylistPlaylistNameRoute
  '/artist/$artistName/': typeof ArtistArtistNameIndexRoute
  '/artist/$artistName/album/$albumSlug': typeof ArtistArtistNameAlbumAlbumSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album/$albumTitle': typeof AlbumAlbumTitleRoute
  '/playlist/$playlistName': typeof PlaylistPlaylistNameRoute
  '/artist/$artistName': typeof ArtistArtistNameIndexRoute
  '/artist/$artistName/album/$albumSlug': typeof ArtistArtistNameAlbumAlbumSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album/$albumTitle': typeof AlbumAlbumTitleRoute
  '/artist/$artistName': typeof ArtistArtistNameRouteWithChildren
  '/playlist/$playlistName': typeof PlaylistPlaylistNameRoute
  '/artist/$artistName/': typeof ArtistArtistNameIndexRoute
  '/artist/$artistName/album/$albumSlug': typeof ArtistArtistNameAlbumAlbumSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album/$albumTitle'
    | '/artist/$artistName'
    | '/playlist/$playlistName'
    | '/artist/$artistName/'
    | '/artist/$artistName/album/$albumSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album/$albumTitle'
    | '/playlist/$playlistName'
    | '/artist/$artistName'
    | '/artist/$artistName/album/$albumSlug'
  id:
    | '__root__'
    | '/'
    | '/album/$albumTitle'
    | '/artist/$artistName'
    | '/playlist/$playlistName'
    | '/artist/$artistName/'
    | '/artist/$artistName/album/$albumSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumAlbumTitleRoute: typeof AlbumAlbumTitleRoute
  ArtistArtistNameRoute: typeof ArtistArtistNameRouteWithChildren
  PlaylistPlaylistNameRoute: typeof PlaylistPlaylistNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$playlistName': {
      id: '/playlist/$playlistName'
      path: '/playlist/$playlistName'
      fullPath: '/playlist/$playlistName'
      preLoaderRoute: typeof PlaylistPlaylistNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$artistName': {
      id: '/artist/$artistName'
      path: '/artist/$artistName'
      fullPath: '/artist/$artistName'
      preLoaderRoute: typeof ArtistArtistNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$albumTitle': {
      id: '/album/$albumTitle'
      path: '/album/$albumTitle'
      fullPath: '/album/$albumTitle'
      preLoaderRoute: typeof AlbumAlbumTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$artistName/': {
      id: '/artist/$artistName/'
      path: '/'
      fullPath: '/artist/$artistName/'
      preLoaderRoute: typeof ArtistArtistNameIndexRouteImport
      parentRoute: typeof ArtistArtistNameRoute
    }
    '/artist/$artistName/album/$albumSlug': {
      id: '/artist/$artistName/album/$albumSlug'
      path: '/album/$albumSlug'
      fullPath: '/artist/$artistName/album/$albumSlug'
      preLoaderRoute: typeof ArtistArtistNameAlbumAlbumSlugRouteImport
      parentRoute: typeof ArtistArtistNameRoute
    }
  }
}

interface ArtistArtistNameRouteChildren {
  ArtistArtistNameIndexRoute: typeof ArtistArtistNameIndexRoute
  ArtistArtistNameAlbumAlbumSlugRoute: typeof ArtistArtistNameAlbumAlbumSlugRoute
}

const ArtistArtistNameRouteChildren: ArtistArtistNameRouteChildren = {
  ArtistArtistNameIndexRoute: ArtistArtistNameIndexRoute,
  ArtistArtistNameAlbumAlbumSlugRoute: ArtistArtistNameAlbumAlbumSlugRoute,
}

const ArtistArtistNameRouteWithChildren =
  ArtistArtistNameRoute._addFileChildren(ArtistArtistNameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumAlbumTitleRoute: AlbumAlbumTitleRoute,
  ArtistArtistNameRoute: ArtistArtistNameRouteWithChildren,
  PlaylistPlaylistNameRoute: PlaylistPlaylistNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
